/**
 * Single source of truth for API paths (relative to VITE_API_URL).
 * Never inline an endpoint string in a feature.
 */
export const endpoints = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
    changePassword: '/auth/change-password',
  },

  // Public
  categories: '/categories',
  courses: '/courses',
  coursesFeatured: '/courses/featured',
  course: (slug: string) => `/courses/${slug}`,
  teachers: '/teachers',
  teacher: (slug: string) => `/teachers/${slug}`,
  groupsUpcoming: '/groups/upcoming',
  posts: '/posts',
  post: (slug: string) => `/posts/${slug}`,
  testimonials: '/testimonials',
  settings: '/settings',
  leads: '/leads',
  contact: '/contact',

  // Admin CRUD
  admin: {
    statistics: '/admin/statistics/overview',
    users: '/admin/users',
    user: (id: string) => `/admin/users/${id}`,
    categories: '/admin/categories',
    category: (id: string) => `/admin/categories/${id}`,
    courses: '/admin/courses',
    course: (id: string) => `/admin/courses/${id}`,
    coursePublish: (id: string) => `/admin/courses/${id}/publish`,
    courseFeature: (id: string) => `/admin/courses/${id}/feature`,
    teachers: '/admin/teachers',
    teacher: (id: string) => `/admin/teachers/${id}`,
    groups: '/admin/groups',
    group: (id: string) => `/admin/groups/${id}`,
    groupStatus: (id: string) => `/admin/groups/${id}/status`,
    categoriesReorder: '/admin/categories/reorder',
    teachersReorder: '/admin/teachers/reorder',
    students: '/admin/students',
    student: (id: string) => `/admin/students/${id}`,
    studentMove: (id: string) => `/admin/students/${id}/move`,
    leads: '/admin/leads',
    lead: (id: string) => `/admin/leads/${id}`,
    leadStatus: (id: string) => `/admin/leads/${id}/status`,
    leadAssign: (id: string) => `/admin/leads/${id}/assign`,
    leadNote: (id: string) => `/admin/leads/${id}/note`,
    leadConvert: (id: string) => `/admin/leads/${id}/convert`,
    posts: '/admin/posts',
    post: (id: string) => `/admin/posts/${id}`,
    postPublish: (id: string) => `/admin/posts/${id}/publish`,
    testimonials: '/admin/testimonials',
    testimonial: (id: string) => `/admin/testimonials/${id}`,
    testimonialPublish: (id: string) => `/admin/testimonials/${id}/publish`,
    messages: '/admin/messages',
    message: (id: string) => `/admin/messages/${id}`,
    messageRead: (id: string) => `/admin/messages/${id}/read`,
    userStatus: (id: string) => `/admin/users/${id}/status`,
    settings: '/admin/settings',
    setting: (key: string) => `/admin/settings/${key}`,
    uploadImage: '/admin/uploads/image',
  },
} as const;
